// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoC-H-qPX_S8p2lAvYrGkDmez2y9H-ubA',
    appId: '1:74542860301:web:ea32fcef098c05a687ed44',
    messagingSenderId: '74542860301',
    projectId: 'e-commerce-b123c',
    authDomain: 'e-commerce-b123c.firebaseapp.com',
    storageBucket: 'e-commerce-b123c.firebasestorage.app',
    measurementId: 'G-D6J6CC01F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdMTGTdq7aKlzHfX4g13iSzIhTaYqvRYc',
    appId: '1:74542860301:android:6850f3102d28e4ed87ed44',
    messagingSenderId: '74542860301',
    projectId: 'e-commerce-b123c',
    storageBucket: 'e-commerce-b123c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITnxpLE7njnYPKZcBI2pz-ZiuZhm6EJs',
    appId: '1:74542860301:ios:8b15ba9b9d0cd3c787ed44',
    messagingSenderId: '74542860301',
    projectId: 'e-commerce-b123c',
    storageBucket: 'e-commerce-b123c.firebasestorage.app',
    iosBundleId: 'com.example.shoesShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITnxpLE7njnYPKZcBI2pz-ZiuZhm6EJs',
    appId: '1:74542860301:ios:8b15ba9b9d0cd3c787ed44',
    messagingSenderId: '74542860301',
    projectId: 'e-commerce-b123c',
    storageBucket: 'e-commerce-b123c.firebasestorage.app',
    iosBundleId: 'com.example.shoesShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoC-H-qPX_S8p2lAvYrGkDmez2y9H-ubA',
    appId: '1:74542860301:web:6ed26cfec79f9a9f87ed44',
    messagingSenderId: '74542860301',
    projectId: 'e-commerce-b123c',
    authDomain: 'e-commerce-b123c.firebaseapp.com',
    storageBucket: 'e-commerce-b123c.firebasestorage.app',
    measurementId: 'G-CL20RH9DJV',
  );
}
